### ISSUE TITLE
Motivation for the CloudProvider field?

### ISSUE THREAD

**Issue by justinsb** [kubernetes/cluster-registry#29]
I'm trying to understand the use case for the CloudProvider field.

What is the cloud provider in a multi-repo, multi-cloudprovider-implementation world?  If there are two AWS cloudprovider implementations, should they have the same name or a different name?  How are the CloudProvider names registered?

What if a single cluster spans multiple clouds?  Should this be of `[]CloudProvider`?

**Comment by perotinus** [comment]
I've thought about this a bit over the past few days and I'm not sure that I have good answers for you. We hadn't thought too deeply about the semantics of this field, and it may be better in the short term to remove it. The API is still in an alpha state, so we have quite a bit of flexibility at this point.

What do you mean by a "multi-repo, multi-cloudprovider-implementation world"? Is this the same as a cluster spanning multiple clouds? If so, then having this field be a list seems reasonable as a start, but I think that we'd have to do more thinking in order to come up with information that is useful. I'm not sure that knowing that a cluster is spanning multiple clouds without having any information about what parts of the cluster are on which cloud is necessarily that interesting.

CloudProvider names aren't currently meant to be registered, but to be provided by users. This does seem problematic, given the potential for people attempting to encode semantically-meaningful information into a string, but I don't think that we want to provide more than that, or else we risk having a maintenance burden as we add new cloud providers to the list.

What do you mean by two AWS cloudprovider implementations? Do you mean something like GKE vs Kubernetes on GCE?

@madhusudancs do you have more context behind this field?
