### ISSUE TITLE
Authentication Config is not versionable

### ISSUE THREAD

**Issue by justinsb** [kubernetes/cluster-registry#30]
The proposed authentication configuration revolves around a `map[string]string`

```
// Config is a map of values that contains the information necessary for a
// client to authenticate to a Kubernetes API server.
// +optional
Config map[string]string `json:"config,omitempty" protobuf:"bytes,2,rep,name=config"
```

My understanding is that in general we are now avoiding untyped maps for anything intended to be system-meaningful.   They are hard to version & update, and we risk repeating the same problems we hit when using labels/annotations where we probably should have been using fields.

Should we consider a pattern more akin to health checks or volumes, with an effective union of strongly-typed options-types?

**Comment by ericchiang** [comment]
> My understanding is that in general we are now avoiding untyped maps for anything intended to be system-meaningful. They are hard to version & update, and we risk repeating the same problems we hit when using labels/annotations where we probably should have been using fields.

This is the same model we use for kubectl auth providers[1] as well as flex volumes[2]. Since many of these types are going to be used to represent third party login mechanisms (e.g. here's how you get your kerberos ticket), I don't know if we want to require users to have to merge strongly typed options into the API to use the registry auth fields.

If there was versioning information, it could probably be embedded in the `Name` field today.

```go
type AuthInfo struct {
	AuthProviders []AuthProviderConfig
}

type AuthProviderConfig struct {
	Name string
	Config map[string]string
}
```

So something like:

```yaml
authInfo:
  authProviders:
  - name: oidc.coreos.com/v1
    config: ...
  - name: oidc.coreos.com/v2
    config: ...
```

Maybe we can do better? How do flex volumes pan on handling versioning?

[1] https://github.com/kubernetes/client-go/tree/master/plugin/pkg/client/auth
[2] https://github.com/kubernetes/kubernetes/blob/master/examples/volumes/flexvolume/nginx-nfs.yaml#L20
