### ISSUE TITLE
crinit init should not fail if the resources already exist

### ISSUE THREAD

**Issue by perotinus** [kubernetes/cluster-registry#48]
Cloned from https://github.com/kubernetes/kubernetes/issues/50746.

`crinit init` should continue if related resources already exist in the host cluster; or it should provide a `--force` flag.

**Comment by perotinus** [comment]
Also see https://github.com/kubernetes/kubernetes/issues/47159

**Comment by G-Harmon** [comment]
I'm running into this. there are quite a few resources that I have to clean up manually when re-running crinit.
Here's the list of commands I needed to run in order to get my cluster cleaned up and ready to launch crinit again:

kc delete svc/first-cluster-reg -n clusterregistry ns/clusterregistry clusterroles/clusterregistry.k8s.io:apiserver clusterrolebindings/clusterregistry.k8s.io:apiserver  clusterrolebindings/clusterregistry.k8s.io:apiserver-auth-delegator clusterrolebindings/clusterregistry.k8s.io:extension-apiserver-authentication-reader apiservices/v1alpha1.clusterregistry.k8s.io; kc delete rolebindings/clusterregistry.k8s.io:extension-apiserver-authentication-reader -n kube-system

**Comment by font** [comment]
Thanks @G-Harmon! Yep, we need to look at introducing a `delete` subcommand or eventually use helm, to make this simpler. I use the following:

`kubectl delete ns/clusterregistry clusterrole/clusterregistry.k8s.io:apiserver clusterrolebinding/clusterregistry.k8s.io:apiserver clusterrolebinding/clusterregistry.k8s.io:apiserver-auth-delegator; kubectl -n kube-system delete rolebinding/clusterregistry.k8s.io:extension-apiserver-authentication-reader apiservice/v1alpha1.clusterregistry.k8s.io`

**Comment by font** [comment]
@jianzhangbjz While a `--force` option doesn't exist for the `init` subcommand, #192 adds the ability to delete the clusterregistry deployment and it has a `--force` option as well.

**Comment by jianzhangbjz** [comment]
@font Oh, sorry, my misunderstanding. Got it, thanks!

**Comment by perotinus** [comment]
Note that this issue is no longer applicable because of the CRD migration done in #225, which removes `crinit` and the standalone API server.
