### ISSUE TITLE
Configure bots to merge approved PRs that have passed tests

### ISSUE THREAD

**Issue by pmorie** [kubernetes/cluster-registry#54]
This can be done before we actually have the tests; the main objective here is to get out of the habit of hitting the merge button by hand.

cc @perotinus

**Comment by perotinus** [comment]
This seems reasonable to me, but I deferred because:
- it seems like only 4 of the 40 or so k/ repos have a merge queue
- @cjwagner mentioned that the merge functionality provided by Mungegithub has to be set up specifically, and that it's being deprecated in favor of Prow this quarter. Given that I didn't expect there to be an abundance of PRs this quarter, it seemed reasonable to wait for that to be working.

**Comment by pmorie** [comment]
K - that seems reasonable.  We might consider spreading the button to one or two more trusted folks for the time being, but nbd for now.

**Comment by cjwagner** [comment]
We plan to have Tide (Prow's replacement for Mungegithub's submit-queue) running on the kubernetes repo by the end of the quarter. Currently it doesn't have a front end and doesn't work with non-required github status contexts, but we are using it in kubernetes/test-infra and kubernetes/federation.
If you want automatic merging in this repo before we have Tide everywhere I can enable it in its current form.

**Comment by perotinus** [comment]
I've enabled Tide for the cluster-registry, and it looks like it's working great. No more manual merging!
