### ISSUE TITLE
clusterregistry should be able to back its storage with custom resources

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/cluster-registry#55]
Generic API servers can store state anywhere. The sample API server (the project I believe this project is based off of) happens only supports etcd, but since the cluster-registry expects to store very small amounts of data (~hundred of objects max?) custom resources don't create a crazy amount of overhead.

I'd like to propose that the clusterregistry should support storing state in custom resources. This would dramatically reduce the amount of overhead it takes to deploy it.

**Comment by pmorie** [comment]
@ericchiang Do you mean CRD?  There are a couple barriers to doing that, the foremost of which is that CRDs do not support multiple API versions.  However, in principle I agree with you, and for the record we're doing that in service-catalog, though I think the real best way is for a future purpose-built resource that is designed as a storage backend for API servers.

**Comment by ericchiang** [comment]
Sorry I don't mean that we should express cluster objects as CRDs. I mean
the aggregated API server should use CRD instances as its blob store.

The clusterregistry binary would provide versioning as an aggregated API
server, but instead of storing data in etcd, it'd store it in a custom
resource.

**Comment by pmorie** [comment]
That's how I had read what you meant. So, the limitations I wrote about
earlier apply to that use case. We would not be able to support multiple
api versions using CRD as a storage backend from what I understand.

I am all about having a resource based backend for extension api servers.
As far as I am aware the API machinery folks have ideas about how to do
that. Maybe we should engage them?

Our experience doing catalog was that we had to do a ton of work to
accomplish a TPR backend, it was very buggy, and required hacking the API
machinery in ways it wasn't designed to be used at all. It slowed us down
significantly and we ultimately removed TPR support. There's a PR to add a
CRD backend but I have reservations about introducing bugs due to a feature
that isn't strictly required (speaking about service catalog here).

If you are interested in pursuing this, I would look at it like an epic
rather than a task. It is not something I would advise hacking in at all.
The best way would be to think of it as a large project and make the
changes in k8s to be able to do it the right way from the get-go. It's
likely going to be an enormous pain otherwise.

I'd be happy to chat on slack about this to tell you more about my
experience in this area and figure out what the best plan of attack is
here. I really do think enabling a resource-based backend is about the only
tractable long term approach to extension data storage, but unfortunately
we just don't have the right tools for it now.

**Comment by davidopp** [comment]
Ignoring specific use cases like cluster registry for the moment, and keeping in mind the caveats mentioned upthread, are CRDs considered an acceptable way for an application running on the cluster to store state? 

It seems like "run your own API server" is very heavyweight if you're just a small infrastructure application needs to store some moderate amount of state that isn't going to overwhelm the API server or main etcd. (For example, maybe an operator or initializer or authorization webhook or ... that needs to store a bit of internal state.)

@lookuptable @kubernetes/sig-api-machinery-misc

**Comment by lavalamp** [comment]
CRDs scale about as efficiently as configmaps, give or take. Does that help?

On Fri, Oct 27, 2017 at 5:58 PM, David Oppenheimer <notifications@github.com
